[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = []

[licenses]
unlicensed = "deny"
copyleft = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "ISC",
    "Zlib",
    "0BSD",
    "CC0-1.0",
]
exceptions = [
    { name = "unicode-ident", allow = ["Unicode-DFS-2016"] },
]
default = "deny"

[bans]
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"
# Certain crates/versions that will be skipped when doing duplicate detection.
skip = [
    { name = "windows_x86_64_msvc", version = "0.42.2" }, # from windows 0.44.0 and windows-sys 0.45.0
    { name = "windows_x86_64_gnullvm", version = "0.42.2" }, # from windows-targets 0.42.2 and windows-sys 0.45.0
    { name = "windows_x86_64_gnu", version = "0.42.2" }, # from windows 0.44.0 and windows-sys 0.45.0
    { name = "windows_i686_msvc", version = "0.42.2" }, # from windows-targets 0.42.2 and 0.45.0
    { name = "windows_i686_gnu", version = "0.42.2" }, # from windows-targets 0.42.2 and windows-sys 0.45.0
    { name = "windows_aarch64_msvc", version = "0.42.2" }, # from windows-targets 0.42.2 and windows-sys 0.45.0
    { name = "bitflags", version = "1.3.2" }, # from core-graphics-types 0.1.1 and d3d12 0.6.0 and gpu-alloc 0.5.4 and gpu-alloc-types 0.2.0 and gpu-descriptor 0.2.3 and gpu-descriptor-types 0.1.1 and hassle-rs 0.10.0 and metal 0.24.0 and naga 0.12.0 and redox_syscall 0.2.16 and spirv 0.2.0+1.5.4
    { name = "syn", version = "1.0.109" }, # from phf_macros 0.11.1
    { name = "windows-sys", version = "0.45.0" }, # from parking_lot_core 0.9.7
    { name = "libloading", version = "0.7.4"}, # from ash 0.37.2+1.3.238 and d3d12 0.6.0 and hassle-rs 0.10.0 and khronos-egl 4.1.0
    { name = "windows-targets", version = "0.42.2" }, # from windows 0.44.0 and windows-sys 0.45.0
    { name = "windows_aarch64_gnullvm", version = "0.42.2" } # from windows-targets 0.42.2 and windows-sys 0.45.0
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []