use winit::event;

pub enum VirtualKeyCode {
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Num0,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Escape,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    Snapshot,
    Scroll,
    Pause,
    Insert,
    Home,
    Delete,
    End,
    PageDown,
    PageUp,
    Left,
    Up,
    Right,
    Down,
    Back,
    Return,
    Space,
    Compose,
    Caret,
    Numlock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadDivide,
    NumpadDecimal,
    NumpadComma,
    NumpadEnter,
    NumpadEquals,
    NumpadMultiply,
    NumpadSubtract,
    AbntC1,
    AbntC2,
    Apostrophe,
    Apps,
    Asterisk,
    At,
    Ax,
    Backslash,
    Calculator,
    Capital,
    Colon,
    Comma,
    Convert,
    Equals,
    Grave,
    Kana,
    Kanji,
    LAlt,
    LBracket,
    LControl,
    LShift,
    LWin,
    Mail,
    MediaSelect,
    MediaStop,
    Minus,
    Mute,
    MyComputer,
    NavigateForward,
    NavigateBackward,
    NextTrack,
    NoConvert,
    OEM102,
    Period,
    PlayPause,
    Plus,
    Power,
    PrevTrack,
    RAlt,
    RBracket,
    RControl,
    RShift,
    RWin,
    Semicolon,
    Slash,
    Sleep,
    Stop,
    Sysrq,
    Tab,
    Underline,
    Unlabeled,
    VolumeDown,
    VolumeUp,
    Wake,
    WebBack,
    WebFavorites,
    WebForward,
    WebHome,
    WebRefresh,
    WebSearch,
    WebStop,
    Yen,
    Copy,
    Paste,
    Cut,
}

impl VirtualKeyCode {
    pub fn by_winit_keycode(virtual_keycode: event::VirtualKeyCode) -> Self {
        match virtual_keycode {
            event::VirtualKeyCode::Key1 => VirtualKeyCode::Num1,
            event::VirtualKeyCode::Key2 => VirtualKeyCode::Num2,
            event::VirtualKeyCode::Key3 => VirtualKeyCode::Num3,
            event::VirtualKeyCode::Key4 => VirtualKeyCode::Num4,
            event::VirtualKeyCode::Key5 => VirtualKeyCode::Num5,
            event::VirtualKeyCode::Key6 => VirtualKeyCode::Num6,
            event::VirtualKeyCode::Key7 => VirtualKeyCode::Num7,
            event::VirtualKeyCode::Key8 => VirtualKeyCode::Num8,
            event::VirtualKeyCode::Key9 => VirtualKeyCode::Num9,
            event::VirtualKeyCode::Key0 => VirtualKeyCode::Num0,
            event::VirtualKeyCode::A => VirtualKeyCode::A,
            event::VirtualKeyCode::B => VirtualKeyCode::B,
            event::VirtualKeyCode::C => VirtualKeyCode::C,
            event::VirtualKeyCode::D => VirtualKeyCode::D,
            event::VirtualKeyCode::E => VirtualKeyCode::E,
            event::VirtualKeyCode::F => VirtualKeyCode::F,
            event::VirtualKeyCode::G => VirtualKeyCode::G,
            event::VirtualKeyCode::H => VirtualKeyCode::H,
            event::VirtualKeyCode::I => VirtualKeyCode::I,
            event::VirtualKeyCode::J => VirtualKeyCode::J,
            event::VirtualKeyCode::K => VirtualKeyCode::K,
            event::VirtualKeyCode::L => VirtualKeyCode::L,
            event::VirtualKeyCode::M => VirtualKeyCode::M,
            event::VirtualKeyCode::N => VirtualKeyCode::N,
            event::VirtualKeyCode::O => VirtualKeyCode::O,
            event::VirtualKeyCode::P => VirtualKeyCode::P,
            event::VirtualKeyCode::Q => VirtualKeyCode::Q,
            event::VirtualKeyCode::R => VirtualKeyCode::R,
            event::VirtualKeyCode::S => VirtualKeyCode::S,
            event::VirtualKeyCode::T => VirtualKeyCode::T,
            event::VirtualKeyCode::U => VirtualKeyCode::U,
            event::VirtualKeyCode::V => VirtualKeyCode::V,
            event::VirtualKeyCode::W => VirtualKeyCode::W,
            event::VirtualKeyCode::X => VirtualKeyCode::X,
            event::VirtualKeyCode::Y => VirtualKeyCode::Y,
            event::VirtualKeyCode::Z => VirtualKeyCode::Z,
            event::VirtualKeyCode::Escape => VirtualKeyCode::Escape,
            event::VirtualKeyCode::F1 => VirtualKeyCode::F1,
            event::VirtualKeyCode::F2 => VirtualKeyCode::F2,
            event::VirtualKeyCode::F3 => VirtualKeyCode::F3,
            event::VirtualKeyCode::F4 => VirtualKeyCode::F4,
            event::VirtualKeyCode::F5 => VirtualKeyCode::F5,
            event::VirtualKeyCode::F6 => VirtualKeyCode::F6,
            event::VirtualKeyCode::F7 => VirtualKeyCode::F7,
            event::VirtualKeyCode::F8 => VirtualKeyCode::F8,
            event::VirtualKeyCode::F9 => VirtualKeyCode::F9,
            event::VirtualKeyCode::F10 => VirtualKeyCode::F10,
            event::VirtualKeyCode::F11 => VirtualKeyCode::F11,
            event::VirtualKeyCode::F12 => VirtualKeyCode::F12,
            event::VirtualKeyCode::F13 => VirtualKeyCode::F13,
            event::VirtualKeyCode::F14 => VirtualKeyCode::F14,
            event::VirtualKeyCode::F15 => VirtualKeyCode::F15,
            event::VirtualKeyCode::F16 => VirtualKeyCode::F16,
            event::VirtualKeyCode::F17 => VirtualKeyCode::F17,
            event::VirtualKeyCode::F18 => VirtualKeyCode::F18,
            event::VirtualKeyCode::F19 => VirtualKeyCode::F19,
            event::VirtualKeyCode::F20 => VirtualKeyCode::F20,
            event::VirtualKeyCode::F21 => VirtualKeyCode::F21,
            event::VirtualKeyCode::F22 => VirtualKeyCode::F22,
            event::VirtualKeyCode::F23 => VirtualKeyCode::F23,
            event::VirtualKeyCode::F24 => VirtualKeyCode::F24,
            event::VirtualKeyCode::Snapshot => VirtualKeyCode::Snapshot,
            event::VirtualKeyCode::Scroll => VirtualKeyCode::Scroll,
            event::VirtualKeyCode::Pause => VirtualKeyCode::Pause,
            event::VirtualKeyCode::Insert => VirtualKeyCode::Insert,
            event::VirtualKeyCode::Home => VirtualKeyCode::Home,
            event::VirtualKeyCode::Delete => VirtualKeyCode::Delete,
            event::VirtualKeyCode::End => VirtualKeyCode::End,
            event::VirtualKeyCode::PageDown => VirtualKeyCode::PageDown,
            event::VirtualKeyCode::PageUp => VirtualKeyCode::PageUp,
            event::VirtualKeyCode::Left => VirtualKeyCode::Left,
            event::VirtualKeyCode::Up => VirtualKeyCode::Up,
            event::VirtualKeyCode::Right => VirtualKeyCode::Right,
            event::VirtualKeyCode::Down => VirtualKeyCode::Down,
            event::VirtualKeyCode::Back => VirtualKeyCode::Back,
            event::VirtualKeyCode::Return => VirtualKeyCode::Return,
            event::VirtualKeyCode::Space => VirtualKeyCode::Space,
            event::VirtualKeyCode::Compose => VirtualKeyCode::Compose,
            event::VirtualKeyCode::Caret => VirtualKeyCode::Caret,
            event::VirtualKeyCode::Numlock => VirtualKeyCode::Numlock,
            event::VirtualKeyCode::Numpad0 => VirtualKeyCode::Numpad0,
            event::VirtualKeyCode::Numpad1 => VirtualKeyCode::Numpad1,
            event::VirtualKeyCode::Numpad2 => VirtualKeyCode::Numpad2,
            event::VirtualKeyCode::Numpad3 => VirtualKeyCode::Numpad3,
            event::VirtualKeyCode::Numpad4 => VirtualKeyCode::Numpad4,
            event::VirtualKeyCode::Numpad5 => VirtualKeyCode::Numpad5,
            event::VirtualKeyCode::Numpad6 => VirtualKeyCode::Numpad6,
            event::VirtualKeyCode::Numpad7 => VirtualKeyCode::Numpad7,
            event::VirtualKeyCode::Numpad8 => VirtualKeyCode::Numpad8,
            event::VirtualKeyCode::Numpad9 => VirtualKeyCode::Numpad9,
            event::VirtualKeyCode::AbntC1 => VirtualKeyCode::AbntC1,
            event::VirtualKeyCode::AbntC2 => VirtualKeyCode::AbntC2,
            event::VirtualKeyCode::NumpadAdd => VirtualKeyCode::NumpadAdd,
            event::VirtualKeyCode::Apostrophe => VirtualKeyCode::Apostrophe,
            event::VirtualKeyCode::Apps => VirtualKeyCode::Apps,
            event::VirtualKeyCode::At => VirtualKeyCode::At,
            event::VirtualKeyCode::Ax => VirtualKeyCode::Ax,
            event::VirtualKeyCode::Backslash => VirtualKeyCode::Backslash,
            event::VirtualKeyCode::Calculator => VirtualKeyCode::Calculator,
            event::VirtualKeyCode::Capital => VirtualKeyCode::Capital,
            event::VirtualKeyCode::Colon => VirtualKeyCode::Colon,
            event::VirtualKeyCode::Comma => VirtualKeyCode::Comma,
            event::VirtualKeyCode::Convert => VirtualKeyCode::Convert,
            event::VirtualKeyCode::NumpadDecimal => VirtualKeyCode::NumpadDecimal,
            event::VirtualKeyCode::NumpadDivide => VirtualKeyCode::NumpadDivide,
            event::VirtualKeyCode::Equals => VirtualKeyCode::Equals,
            event::VirtualKeyCode::Grave => VirtualKeyCode::Grave,
            event::VirtualKeyCode::Kana => VirtualKeyCode::Kana,
            event::VirtualKeyCode::Kanji => VirtualKeyCode::Kanji,
            event::VirtualKeyCode::LAlt => VirtualKeyCode::LAlt,
            event::VirtualKeyCode::LBracket => VirtualKeyCode::LBracket,
            event::VirtualKeyCode::LControl => VirtualKeyCode::LControl,
            event::VirtualKeyCode::LShift => VirtualKeyCode::LShift,
            event::VirtualKeyCode::LWin => VirtualKeyCode::LWin,
            event::VirtualKeyCode::Mail => VirtualKeyCode::Mail,
            event::VirtualKeyCode::MediaSelect => VirtualKeyCode::MediaSelect,
            event::VirtualKeyCode::MediaStop => VirtualKeyCode::MediaStop,
            event::VirtualKeyCode::Minus => VirtualKeyCode::Minus,
            event::VirtualKeyCode::NumpadMultiply => VirtualKeyCode::NumpadMultiply,
            event::VirtualKeyCode::Mute => VirtualKeyCode::Mute,
            event::VirtualKeyCode::MyComputer => VirtualKeyCode::MyComputer,
            event::VirtualKeyCode::NavigateForward => VirtualKeyCode::NavigateForward,
            event::VirtualKeyCode::NavigateBackward => VirtualKeyCode::NavigateBackward,
            event::VirtualKeyCode::NextTrack => VirtualKeyCode::NextTrack,
            event::VirtualKeyCode::NoConvert => VirtualKeyCode::NoConvert,
            event::VirtualKeyCode::NumpadComma => VirtualKeyCode::NumpadComma,
            event::VirtualKeyCode::NumpadEnter => VirtualKeyCode::NumpadEnter,
            event::VirtualKeyCode::NumpadEquals => VirtualKeyCode::NumpadEquals,
            event::VirtualKeyCode::OEM102 => VirtualKeyCode::OEM102,
            event::VirtualKeyCode::Period => VirtualKeyCode::Period,
            event::VirtualKeyCode::PlayPause => VirtualKeyCode::PlayPause,
            event::VirtualKeyCode::Power => VirtualKeyCode::Power,
            event::VirtualKeyCode::PrevTrack => VirtualKeyCode::PrevTrack,
            event::VirtualKeyCode::RAlt => VirtualKeyCode::RAlt,
            event::VirtualKeyCode::RBracket => VirtualKeyCode::RBracket,
            event::VirtualKeyCode::RControl => VirtualKeyCode::RControl,
            event::VirtualKeyCode::RShift => VirtualKeyCode::RShift,
            event::VirtualKeyCode::RWin => VirtualKeyCode::RWin,
            event::VirtualKeyCode::Semicolon => VirtualKeyCode::Semicolon,
            event::VirtualKeyCode::Slash => VirtualKeyCode::Slash,
            event::VirtualKeyCode::Sleep => VirtualKeyCode::Sleep,
            event::VirtualKeyCode::Stop => VirtualKeyCode::Stop,
            event::VirtualKeyCode::NumpadSubtract => VirtualKeyCode::NumpadSubtract,
            event::VirtualKeyCode::Sysrq => VirtualKeyCode::Sysrq,
            event::VirtualKeyCode::Tab => VirtualKeyCode::Tab,
            event::VirtualKeyCode::Underline => VirtualKeyCode::Underline,
            event::VirtualKeyCode::Unlabeled => VirtualKeyCode::Unlabeled,
            event::VirtualKeyCode::VolumeDown => VirtualKeyCode::VolumeDown,
            event::VirtualKeyCode::VolumeUp => VirtualKeyCode::VolumeUp,
            event::VirtualKeyCode::Wake => VirtualKeyCode::Wake,
            event::VirtualKeyCode::WebBack => VirtualKeyCode::WebBack,
            event::VirtualKeyCode::WebFavorites => VirtualKeyCode::WebFavorites,
            event::VirtualKeyCode::WebForward => VirtualKeyCode::WebForward,
            event::VirtualKeyCode::WebHome => VirtualKeyCode::WebHome,
            event::VirtualKeyCode::WebRefresh => VirtualKeyCode::WebRefresh,
            event::VirtualKeyCode::WebSearch => VirtualKeyCode::WebSearch,
            event::VirtualKeyCode::WebStop => VirtualKeyCode::WebStop,
            event::VirtualKeyCode::Yen => VirtualKeyCode::Yen,
            event::VirtualKeyCode::Copy => VirtualKeyCode::Copy,
            event::VirtualKeyCode::Paste => VirtualKeyCode::Paste,
            event::VirtualKeyCode::Cut => VirtualKeyCode::Cut,
            event::VirtualKeyCode::Asterisk => VirtualKeyCode::Asterisk,
            event::VirtualKeyCode::Plus => VirtualKeyCode::Plus,
        }
    }
}
