use winit::event;

pub enum VirtualKeyCode {
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Num0,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Escape,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    Snapshot,
    Scroll,
    Pause,
    Insert,
    Home,
    Delete,
    End,
    PageDown,
    PageUp,
    Left,
    Up,
    Right,
    Down,
    Back,
    Return,
    Space,
    Compose,
    Caret,
    Numlock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadDivide,
    NumpadDecimal,
    NumpadComma,
    NumpadEnter,
    NumpadEquals,
    NumpadMultiply,
    NumpadSubtract,
    AbntC1,
    AbntC2,
    Apostrophe,
    Apps,
    Asterisk,
    At,
    Ax,
    Backslash,
    Calculator,
    Capital,
    Colon,
    Comma,
    Convert,
    Equals,
    Grave,
    Kana,
    Kanji,
    LAlt,
    LBracket,
    LControl,
    LShift,
    LWin,
    Mail,
    MediaSelect,
    MediaStop,
    Minus,
    Mute,
    MyComputer,
    NavigateForward,
    NavigateBackward,
    NextTrack,
    NoConvert,
    OEM102,
    Period,
    PlayPause,
    Plus,
    Power,
    PrevTrack,
    RAlt,
    RBracket,
    RControl,
    RShift,
    RWin,
    Semicolon,
    Slash,
    Sleep,
    Stop,
    Sysrq,
    Tab,
    Underline,
    Unlabeled,
    VolumeDown,
    VolumeUp,
    Wake,
    WebBack,
    WebFavorites,
    WebForward,
    WebHome,
    WebRefresh,
    WebSearch,
    WebStop,
    Yen,
    Copy,
    Paste,
    Cut,
}

impl VirtualKeyCode {
    /**
     * Converte um keycode do winit para um keycode do cgdraw.
     */
    pub fn by_winit_keycode(virtual_keycode: event::VirtualKeyCode) -> Option<Self> {
        match virtual_keycode {
            event::VirtualKeyCode::Key1 => Some(VirtualKeyCode::Num1),
            event::VirtualKeyCode::Key2 => Some(VirtualKeyCode::Num2),
            event::VirtualKeyCode::Key3 => Some(VirtualKeyCode::Num3),
            event::VirtualKeyCode::Key4 => Some(VirtualKeyCode::Num4),
            event::VirtualKeyCode::Key5 => Some(VirtualKeyCode::Num5),
            event::VirtualKeyCode::Key6 => Some(VirtualKeyCode::Num6),
            event::VirtualKeyCode::Key7 => Some(VirtualKeyCode::Num7),
            event::VirtualKeyCode::Key8 => Some(VirtualKeyCode::Num8),
            event::VirtualKeyCode::Key9 => Some(VirtualKeyCode::Num9),
            event::VirtualKeyCode::Key0 => Some(VirtualKeyCode::Num0),
            event::VirtualKeyCode::A => Some(VirtualKeyCode::A),
            event::VirtualKeyCode::B => Some(VirtualKeyCode::B),
            event::VirtualKeyCode::C => Some(VirtualKeyCode::C),
            event::VirtualKeyCode::D => Some(VirtualKeyCode::D),
            event::VirtualKeyCode::E => Some(VirtualKeyCode::E),
            event::VirtualKeyCode::F => Some(VirtualKeyCode::F),
            event::VirtualKeyCode::G => Some(VirtualKeyCode::G),
            event::VirtualKeyCode::H => Some(VirtualKeyCode::H),
            event::VirtualKeyCode::I => Some(VirtualKeyCode::I),
            event::VirtualKeyCode::J => Some(VirtualKeyCode::J),
            event::VirtualKeyCode::K => Some(VirtualKeyCode::K),
            event::VirtualKeyCode::L => Some(VirtualKeyCode::L),
            event::VirtualKeyCode::M => Some(VirtualKeyCode::M),
            event::VirtualKeyCode::N => Some(VirtualKeyCode::N),
            event::VirtualKeyCode::O => Some(VirtualKeyCode::O),
            event::VirtualKeyCode::P => Some(VirtualKeyCode::P),
            event::VirtualKeyCode::Q => Some(VirtualKeyCode::Q),
            event::VirtualKeyCode::R => Some(VirtualKeyCode::R),
            event::VirtualKeyCode::S => Some(VirtualKeyCode::S),
            event::VirtualKeyCode::T => Some(VirtualKeyCode::T),
            event::VirtualKeyCode::U => Some(VirtualKeyCode::U),
            event::VirtualKeyCode::V => Some(VirtualKeyCode::V),
            event::VirtualKeyCode::W => Some(VirtualKeyCode::W),
            event::VirtualKeyCode::X => Some(VirtualKeyCode::X),
            event::VirtualKeyCode::Y => Some(VirtualKeyCode::Y),
            event::VirtualKeyCode::Z => Some(VirtualKeyCode::Z),
            event::VirtualKeyCode::Escape => Some(VirtualKeyCode::Escape),
            event::VirtualKeyCode::F1 => Some(VirtualKeyCode::F1),
            event::VirtualKeyCode::F2 => Some(VirtualKeyCode::F2),
            event::VirtualKeyCode::F3 => Some(VirtualKeyCode::F3),
            event::VirtualKeyCode::F4 => Some(VirtualKeyCode::F4),
            event::VirtualKeyCode::F5 => Some(VirtualKeyCode::F5),
            event::VirtualKeyCode::F6 => Some(VirtualKeyCode::F6),
            event::VirtualKeyCode::F7 => Some(VirtualKeyCode::F7),
            event::VirtualKeyCode::F8 => Some(VirtualKeyCode::F8),
            event::VirtualKeyCode::F9 => Some(VirtualKeyCode::F9),
            event::VirtualKeyCode::F10 => Some(VirtualKeyCode::F10),
            event::VirtualKeyCode::F11 => Some(VirtualKeyCode::F11),
            event::VirtualKeyCode::F12 => Some(VirtualKeyCode::F12),
            event::VirtualKeyCode::F13 => Some(VirtualKeyCode::F13),
            event::VirtualKeyCode::F14 => Some(VirtualKeyCode::F14),
            event::VirtualKeyCode::F15 => Some(VirtualKeyCode::F15),
            event::VirtualKeyCode::F16 => Some(VirtualKeyCode::F16),
            event::VirtualKeyCode::F17 => Some(VirtualKeyCode::F17),
            event::VirtualKeyCode::F18 => Some(VirtualKeyCode::F18),
            event::VirtualKeyCode::F19 => Some(VirtualKeyCode::F19),
            event::VirtualKeyCode::F20 => Some(VirtualKeyCode::F20),
            event::VirtualKeyCode::F21 => Some(VirtualKeyCode::F21),
            event::VirtualKeyCode::F22 => Some(VirtualKeyCode::F22),
            event::VirtualKeyCode::F23 => Some(VirtualKeyCode::F23),
            event::VirtualKeyCode::F24 => Some(VirtualKeyCode::F24),
            event::VirtualKeyCode::Snapshot => Some(VirtualKeyCode::Snapshot),
            event::VirtualKeyCode::Scroll => Some(VirtualKeyCode::Scroll),
            event::VirtualKeyCode::Pause => Some(VirtualKeyCode::Pause),
            event::VirtualKeyCode::Insert => Some(VirtualKeyCode::Insert),
            event::VirtualKeyCode::Home => Some(VirtualKeyCode::Home),
            event::VirtualKeyCode::Delete => Some(VirtualKeyCode::Delete),
            event::VirtualKeyCode::End => Some(VirtualKeyCode::End),
            event::VirtualKeyCode::PageDown => Some(VirtualKeyCode::PageDown),
            event::VirtualKeyCode::PageUp => Some(VirtualKeyCode::PageUp),
            event::VirtualKeyCode::Left => Some(VirtualKeyCode::Left),
            event::VirtualKeyCode::Up => Some(VirtualKeyCode::Up),
            event::VirtualKeyCode::Right => Some(VirtualKeyCode::Right),
            event::VirtualKeyCode::Down => Some(VirtualKeyCode::Down),
            event::VirtualKeyCode::Back => Some(VirtualKeyCode::Back),
            event::VirtualKeyCode::Return => Some(VirtualKeyCode::Return),
            event::VirtualKeyCode::Space => Some(VirtualKeyCode::Space),
            event::VirtualKeyCode::Compose => Some(VirtualKeyCode::Compose),
            event::VirtualKeyCode::Caret => Some(VirtualKeyCode::Caret),
            event::VirtualKeyCode::Numlock => Some(VirtualKeyCode::Numlock),
            event::VirtualKeyCode::Numpad0 => Some(VirtualKeyCode::Numpad0),
            event::VirtualKeyCode::Numpad1 => Some(VirtualKeyCode::Numpad1),
            event::VirtualKeyCode::Numpad2 => Some(VirtualKeyCode::Numpad2),
            event::VirtualKeyCode::Numpad3 => Some(VirtualKeyCode::Numpad3),
            event::VirtualKeyCode::Numpad4 => Some(VirtualKeyCode::Numpad4),
            event::VirtualKeyCode::Numpad5 => Some(VirtualKeyCode::Numpad5),
            event::VirtualKeyCode::Numpad6 => Some(VirtualKeyCode::Numpad6),
            event::VirtualKeyCode::Numpad7 => Some(VirtualKeyCode::Numpad7),
            event::VirtualKeyCode::Numpad8 => Some(VirtualKeyCode::Numpad8),
            event::VirtualKeyCode::Numpad9 => Some(VirtualKeyCode::Numpad9),
            event::VirtualKeyCode::AbntC1 => Some(VirtualKeyCode::AbntC1),
            event::VirtualKeyCode::AbntC2 => Some(VirtualKeyCode::AbntC2),
            event::VirtualKeyCode::NumpadAdd => Some(VirtualKeyCode::NumpadAdd),
            event::VirtualKeyCode::Apostrophe => Some(VirtualKeyCode::Apostrophe),
            event::VirtualKeyCode::Apps => Some(VirtualKeyCode::Apps),
            event::VirtualKeyCode::At => Some(VirtualKeyCode::At),
            event::VirtualKeyCode::Ax => Some(VirtualKeyCode::Ax),
            event::VirtualKeyCode::Backslash => Some(VirtualKeyCode::Backslash),
            event::VirtualKeyCode::Calculator => Some(VirtualKeyCode::Calculator),
            event::VirtualKeyCode::Capital => Some(VirtualKeyCode::Capital),
            event::VirtualKeyCode::Colon => Some(VirtualKeyCode::Colon),
            event::VirtualKeyCode::Comma => Some(VirtualKeyCode::Comma),
            event::VirtualKeyCode::Convert => Some(VirtualKeyCode::Convert),
            event::VirtualKeyCode::NumpadDecimal => Some(VirtualKeyCode::NumpadDecimal),
            event::VirtualKeyCode::NumpadDivide => Some(VirtualKeyCode::NumpadDivide),
            event::VirtualKeyCode::Equals => Some(VirtualKeyCode::Equals),
            event::VirtualKeyCode::Grave => Some(VirtualKeyCode::Grave),
            event::VirtualKeyCode::Kana => Some(VirtualKeyCode::Kana),
            event::VirtualKeyCode::Kanji => Some(VirtualKeyCode::Kanji),
            event::VirtualKeyCode::LAlt => Some(VirtualKeyCode::LAlt),
            event::VirtualKeyCode::LBracket => Some(VirtualKeyCode::LBracket),
            event::VirtualKeyCode::LControl => Some(VirtualKeyCode::LControl),
            event::VirtualKeyCode::LShift => Some(VirtualKeyCode::LShift),
            event::VirtualKeyCode::LWin => Some(VirtualKeyCode::LWin),
            event::VirtualKeyCode::Mail => Some(VirtualKeyCode::Mail),
            event::VirtualKeyCode::MediaSelect => Some(VirtualKeyCode::MediaSelect),
            event::VirtualKeyCode::MediaStop => Some(VirtualKeyCode::MediaStop),
            event::VirtualKeyCode::Minus => Some(VirtualKeyCode::Minus),
            event::VirtualKeyCode::NumpadMultiply => Some(VirtualKeyCode::NumpadMultiply),
            event::VirtualKeyCode::Mute => Some(VirtualKeyCode::Mute),
            event::VirtualKeyCode::MyComputer => Some(VirtualKeyCode::MyComputer),
            event::VirtualKeyCode::NavigateForward => Some(VirtualKeyCode::NavigateForward),
            event::VirtualKeyCode::NavigateBackward => Some(VirtualKeyCode::NavigateBackward),
            event::VirtualKeyCode::NextTrack => Some(VirtualKeyCode::NextTrack),
            event::VirtualKeyCode::NoConvert => Some(VirtualKeyCode::NoConvert),
            event::VirtualKeyCode::NumpadComma => Some(VirtualKeyCode::NumpadComma),
            event::VirtualKeyCode::NumpadEnter => Some(VirtualKeyCode::NumpadEnter),
            event::VirtualKeyCode::NumpadEquals => Some(VirtualKeyCode::NumpadEquals),
            event::VirtualKeyCode::OEM102 => Some(VirtualKeyCode::OEM102),
            event::VirtualKeyCode::Period => Some(VirtualKeyCode::Period),
            event::VirtualKeyCode::PlayPause => Some(VirtualKeyCode::PlayPause),
            event::VirtualKeyCode::Power => Some(VirtualKeyCode::Power),
            event::VirtualKeyCode::PrevTrack => Some(VirtualKeyCode::PrevTrack),
            event::VirtualKeyCode::RAlt => Some(VirtualKeyCode::RAlt),
            event::VirtualKeyCode::RBracket => Some(VirtualKeyCode::RBracket),
            event::VirtualKeyCode::RControl => Some(VirtualKeyCode::RControl),
            event::VirtualKeyCode::RShift => Some(VirtualKeyCode::RShift),
            event::VirtualKeyCode::RWin => Some(VirtualKeyCode::RWin),
            event::VirtualKeyCode::Semicolon => Some(VirtualKeyCode::Semicolon),
            event::VirtualKeyCode::Slash => Some(VirtualKeyCode::Slash),
            event::VirtualKeyCode::Sleep => Some(VirtualKeyCode::Sleep),
            event::VirtualKeyCode::Stop => Some(VirtualKeyCode::Stop),
            event::VirtualKeyCode::NumpadSubtract => Some(VirtualKeyCode::NumpadSubtract),
            event::VirtualKeyCode::Sysrq => Some(VirtualKeyCode::Sysrq),
            event::VirtualKeyCode::Tab => Some(VirtualKeyCode::Tab),
            event::VirtualKeyCode::Underline => Some(VirtualKeyCode::Underline),
            event::VirtualKeyCode::Unlabeled => Some(VirtualKeyCode::Unlabeled),
            event::VirtualKeyCode::VolumeDown => Some(VirtualKeyCode::VolumeDown),
            event::VirtualKeyCode::VolumeUp => Some(VirtualKeyCode::VolumeUp),
            event::VirtualKeyCode::Wake => Some(VirtualKeyCode::Wake),
            event::VirtualKeyCode::WebBack => Some(VirtualKeyCode::WebBack),
            event::VirtualKeyCode::WebFavorites => Some(VirtualKeyCode::WebFavorites),
            event::VirtualKeyCode::WebForward => Some(VirtualKeyCode::WebForward),
            event::VirtualKeyCode::WebHome => Some(VirtualKeyCode::WebHome),
            event::VirtualKeyCode::WebRefresh => Some(VirtualKeyCode::WebRefresh),
            event::VirtualKeyCode::WebSearch => Some(VirtualKeyCode::WebSearch),
            event::VirtualKeyCode::WebStop => Some(VirtualKeyCode::WebStop),
            event::VirtualKeyCode::Yen => Some(VirtualKeyCode::Yen),
            event::VirtualKeyCode::Copy => Some(VirtualKeyCode::Copy),
            event::VirtualKeyCode::Paste => Some(VirtualKeyCode::Paste),
            event::VirtualKeyCode::Cut => Some(VirtualKeyCode::Cut),
            event::VirtualKeyCode::Asterisk => Some(VirtualKeyCode::Asterisk),
            event::VirtualKeyCode::Plus => Some(VirtualKeyCode::Plus),
        }
    }
}
